services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      N8N_WEBHOOK_URL: ${N8N_WEBHOOK_URL}
      N8N_AI_RESPONSE_URL: ${N8N_AI_RESPONSE_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./DB.xlsx:/app/DB.xlsx

volumes:
  postgres_data:
  n8n_data:
